/**
 * Activity Feed (v2 - server-assembled)
 *
 * The feed payload is built server-side by /api/feed/v2 in a handful of
 * batched queries (no per-card N+1 fetching). Card lineup:
 * - Friend digest cards ("What Todd's been watching this week")
 * - Platform chart card (Top on Netflix/Max/... from real chart data)
 * - Viewers Like You (collaborative filtering)
 * - Because You Liked / Coming Soon
 * - Follow suggestions
 *
 * URL: /feed
 */

'use client'

import React, { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/utils/supabase/client'
import { useThemeColors } from '@/hooks/useThemeColors'
import { FeedCard, BADGE_PRESETS, FeedCardData } from '@/components/feed/UserActivityCard'
import { FollowSuggestionsCard } from '@/components/feed/FollowSuggestionsCard'
import FriendDigestCard from '@/components/feed/FriendDigestCard'
import PlatformChartCard from '@/components/feed/PlatformChartCard'
import HeroTopChartsCard from '@/components/feed/HeroTopChartsCard'
import ShowDetailCard from '@/components/media/ShowDetailCard'
import ProfileSetup from '@/components/onboarding/ProfileSetup'
import InviteCodeGate from '@/components/onboarding/InviteCodeGate'
import BottomNav from '@/components/navigation/BottomNav'
import AppHeader from '@/components/navigation/AppHeader'
import SearchModalEnhanced from '@/components/search/SearchModalEnhanced'
import { isAutoGeneratedUsername } from '@/utils/usernameValidation'
import { mapGenreIds } from '@/lib/feed/genres'
import { ensureReleaseReminder } from '@/lib/reminders'
import type { FeedV2Response, DigestShowItem, ChartEntry, PlatformChart, VlyItem, ComingSoonItem, BylItem } from '@/lib/feed/types'
import {
  trackFeedViewed,
  trackUserFollowed,
  trackMediaRated,
  trackWatchStatusChanged,
  trackEvent
} from '@/utils/analytics'

interface Profile {
  id: string
  username: string
  display_name: string
  avatar_url: string | null
  has_seen_onboarding?: boolean
  is_approved?: boolean
}

interface DetailShow {
  id: string
  title: string
  posterUrl?: string
  year?: string
  genres?: string[]
  rating?: number
  synopsis?: string
  mediaType?: 'Movie' | 'TV'
  season?: number
  streamingPlatforms?: string[]
  tmdb_id?: number
}

const FEED_CACHE_KEY = 'bw_feed_v2_cache'

type FeedBlock =
  | { kind: 'digest'; key: string; digest: FeedV2Response['digests'][number] }
  | { kind: 'hero'; key: string }
  | { kind: 'chart'; key: string; chart: PlatformChart; chartType: 'tv' | 'movie' }
  | { kind: 'vly'; key: string; item: VlyItem }
  | { kind: 'byl'; key: string; item: BylItem }
  | { kind: 'coming_soon'; key: string; item: ComingSoonItem }
  | { kind: 'follow_suggestions'; key: string }

/**
 * Pick today's chart cards: every platform's overall chart appears daily
 * (TV/movies alternating by day so both get airtime; Netflix always leads
 * with TV - its official Tudum hours are the strongest data), plus a few
 * genre cards rotating daily.
 */
function pickChartBlocks(charts: PlatformChart[], genreCards: number): FeedBlock[] {
  const candidates: Array<{ chart: PlatformChart; chartType: 'tv' | 'movie' }> = []
  for (const chart of charts) {
    if (chart.tv.length >= 3) candidates.push({ chart, chartType: 'tv' })
    if (chart.movies.length >= 3) candidates.push({ chart, chartType: 'movie' })
  }
  if (candidates.length === 0) return []

  const toBlock = (c: { chart: PlatformChart; chartType: 'tv' | 'movie' }): FeedBlock => ({
    kind: 'chart',
    key: `chart-${c.chart.platform}-${c.chart.category}-${c.chartType}`,
    chart: c.chart,
    chartType: c.chartType
  })

  const dayIndex = Math.floor(Date.now() / 86400000)
  const rotate = <T,>(arr: T[]): T[] => {
    if (arr.length === 0) return arr
    const off = dayIndex % arr.length
    return [...arr.slice(off), ...arr.slice(0, off)]
  }

  // One overall card per platform per day, alternating TV/movies by day parity
  const picked: typeof candidates = []
  const overallPlatforms = Array.from(new Set(
    candidates.filter(c => c.chart.category === 'overall').map(c => c.chart.platform)
  ))
  for (const platform of overallPlatforms) {
    const options = candidates.filter(c => c.chart.platform === platform && c.chart.category === 'overall')
    const preferTv = platform === 'netflix' || dayIndex % 2 === 0
    const pick =
      options.find(c => c.chartType === (preferTv ? 'tv' : 'movie')) || options[0]
    if (pick) picked.push(pick)
  }
  // Netflix first, rest keep chart order (overall charts are pre-sorted)
  picked.sort((a, b) => (a.chart.platform === 'netflix' ? -1 : b.chart.platform === 'netflix' ? 1 : 0))

  // Rotating genre cards
  const genre = rotate(candidates.filter(c => c.chart.category !== 'overall'))
  picked.push(...genre.slice(0, genreCards))

  return picked.map(toBlock)
}

export default function FeedPage() {
  const colors = useThemeColors()
  const [user, setUser] = useState<any>(null)
  const [profile, setProfile] = useState<Profile | null>(null)
  const [feedData, setFeedData] = useState<FeedV2Response | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchOpen, setSearchOpen] = useState(false)

  // Onboarding gates
  const [showInviteCodeGate, setShowInviteCodeGate] = useState(false)
  const [showProfileSetup, setShowProfileSetup] = useState(false)

  // Show detail modal
  const [detailShow, setDetailShow] = useState<DetailShow | null>(null)

  const [dismissedSuggestions, setDismissedSuggestions] = useState<Set<string>>(new Set())

  const supabase = createClient()

  // Scroll to top on page load
  useEffect(() => {
    if ('scrollRestoration' in history) {
      history.scrollRestoration = 'manual'
    }
    window.scrollTo(0, 0)
    const timeout = setTimeout(() => window.scrollTo(0, 0), 50)
    return () => clearTimeout(timeout)
  }, [])

  useEffect(() => {
    // Hydrate instantly from the last response (stale-while-revalidate)
    try {
      const cached = sessionStorage.getItem(FEED_CACHE_KEY)
      if (cached) {
        setFeedData(JSON.parse(cached) as FeedV2Response)
        setLoading(false)
      }
    } catch {
      // Corrupt cache - ignore, fresh fetch will replace it
    }
    // The feed API authenticates via cookies, so it can run in parallel with loadUser()
    loadUser()
    loadFeed()
    localStorage.setItem('bw_last_home', '/feed')
  }, [])

  // ---------- auth + onboarding (invite gate, profile setup) ----------

  const redeemPendingInvite = async (userId: string): Promise<boolean> => {
    const vipCode = sessionStorage.getItem('vip_code')
    const inviteToken = sessionStorage.getItem('invite_token')

    if (vipCode) {
      try {
        const { error: rpcError } = await supabase.rpc('use_master_code', {
          master_code: vipCode,
          user_id: userId
        })
        if (rpcError) console.error('Failed to increment code usage:', rpcError)

        const tier = vipCode === 'BOOZEHOUND' ? 'boozehound' :
                    vipCode.startsWith('BWALPHA_') ? 'alpha' : 'beta'

        await supabase
          .from('profiles')
          .update({
            invited_by_master_code: vipCode,
            invite_tier: tier,
            invites_remaining: tier === 'boozehound' ? 10 : tier === 'alpha' ? 3 : 0,
            is_approved: true
          })
          .eq('id', userId)

        sessionStorage.removeItem('vip_code')
        return true
      } catch (err) {
        console.error('Error redeeming VIP code:', err)
        return false
      }
    } else if (inviteToken) {
      try {
        const { data: redeemResult, error: redeemError } = await supabase
          .rpc('redeem_invite_token', {
            invite_token: inviteToken,
            referee_user_id: userId
          })

        if (redeemError) {
          console.error('Error redeeming invite token:', redeemError)
          return false
        }

        if (redeemResult?.success) {
          sessionStorage.removeItem('invite_token')
          await supabase
            .from('profiles')
            .update({ invites_remaining: 0, is_approved: true })
            .eq('id', userId)
          return true
        }
      } catch (err) {
        console.error('Error redeeming invite token:', err)
        return false
      }
    }

    return false
  }

  const loadUser = async () => {
    const { data: { user }, error } = await supabase.auth.getUser()
    if (error || !user) {
      setError('Please log in to view the feed')
      setLoading(false)
      return
    }
    setUser(user)

    const fallbackProfile: Profile = {
      id: user.id,
      username: user.email?.split('@')[0] || `user_${user.id.slice(0, 8)}`,
      display_name: user.user_metadata?.full_name || user.user_metadata?.name || user.email?.split('@')[0] || 'New User',
      avatar_url: user.user_metadata?.avatar_url || user.user_metadata?.picture || null
    }

    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('id, username, display_name, avatar_url, has_seen_onboarding, is_approved')
      .eq('id', user.id)
      .single()

    if (profileError) {
      if (profileError.code === 'PGRST116') {
        // No profile exists - create one
        const { data: newProfile, error: insertError } = await supabase
          .from('profiles')
          .insert({
            id: user.id,
            username: fallbackProfile.username,
            display_name: fallbackProfile.display_name,
            avatar_url: fallbackProfile.avatar_url,
            has_seen_onboarding: false,
            is_approved: false
          })
          .select('id, username, display_name, avatar_url, has_seen_onboarding, is_approved')
          .single()

        if (insertError) console.error('Failed to create profile:', insertError)

        const createdProfile = newProfile || { ...fallbackProfile, is_approved: false }
        setProfile(createdProfile)

        const inviteRedeemed = await redeemPendingInvite(user.id)
        if (inviteRedeemed) {
          setProfile({ ...createdProfile, is_approved: true })
          setShowProfileSetup(true)
        } else {
          setShowInviteCodeGate(true)
        }
      } else {
        console.warn('Profile fetch error, using fallback:', profileError.message)
        setProfile(fallbackProfile)
        setShowInviteCodeGate(true)
      }
    } else {
      setProfile(profileData)

      if (!profileData.is_approved) {
        const inviteRedeemed = await redeemPendingInvite(user.id)
        if (inviteRedeemed) {
          setProfile({ ...profileData, is_approved: true })
          setShowProfileSetup(true)
        } else {
          setShowInviteCodeGate(true)
        }
      } else if (!profileData.username || isAutoGeneratedUsername(profileData.username)) {
        setShowProfileSetup(true)
      }
    }
  }

  // ---------- feed loading ----------

  const loadFeed = async () => {
    try {
      setError(null)
      const res = await fetch('/api/feed/v2')
      if (res.status === 401) {
        setError('Please log in to view the feed')
        return
      }
      if (!res.ok) throw new Error(`Feed failed to load (${res.status})`)
      const data: FeedV2Response = await res.json()
      setFeedData(data)
      try {
        sessionStorage.setItem(FEED_CACHE_KEY, JSON.stringify(data))
      } catch {
        // Storage full/unavailable - not critical
      }
    } catch (err: any) {
      console.error('Error loading feed:', err)
      setError(err.message || 'Failed to load feed')
    } finally {
      setLoading(false)
    }
  }

  // Track feed viewed
  useEffect(() => {
    if (feedData && !loading) {
      trackFeedViewed({
        feed_type: 'enhanced',
        items_shown: feedData.digests.length + feedData.viewersLikeYou.length + feedData.comingSoon.length
      })
    }
  }, [feedData, loading])

  // ---------- card sequence ----------

  const blocks: FeedBlock[] = useMemo(() => {
    if (!feedData) return []
    const result: FeedBlock[] = []
    const digests = feedData.digests
    const vly = feedData.viewersLikeYou.slice(0, 2)
    const byl = feedData.becauseYouLiked.slice(0, 2)
    const comingSoon = feedData.comingSoon.slice(0, 2)
    const chartBlocks = pickChartBlocks(feedData.charts, 3)

    // Base sequence without charts
    if (digests[0]) result.push({ kind: 'digest', key: `digest-${digests[0].user.id}`, digest: digests[0] })
    if (digests[1]) result.push({ kind: 'digest', key: `digest-${digests[1].user.id}`, digest: digests[1] })
    if (vly[0]) result.push({ kind: 'vly', key: `vly-${vly[0].mediaId}`, item: vly[0] })
    if (comingSoon[0]) result.push({ kind: 'coming_soon', key: `cs-${comingSoon[0].mediaId}`, item: comingSoon[0] })
    if (digests[2]) result.push({ kind: 'digest', key: `digest-${digests[2].user.id}`, digest: digests[2] })
    if (byl[0]) result.push({ kind: 'byl', key: `byl-${byl[0].tmdbId}`, item: byl[0] })
    if (vly[1]) result.push({ kind: 'vly', key: `vly-${vly[1].mediaId}`, item: vly[1] })
    // Remaining digests
    for (const d of digests.slice(3)) {
      result.push({ kind: 'digest', key: `digest-${d.user.id}`, digest: d })
    }
    if (byl[1]) result.push({ kind: 'byl', key: `byl-${byl[1].tmdbId}`, item: byl[1] })
    if (comingSoon[1]) result.push({ kind: 'coming_soon', key: `cs-${comingSoon[1].mediaId}`, item: comingSoon[1] })

    // Interleave chart cards: first one right after the lead digest, then one
    // every third slot so they're spread through the feed instead of stacked.
    let insertAt = Math.min(1, result.length)
    for (const chartBlock of chartBlocks) {
      result.splice(insertAt, 0, chartBlock)
      insertAt = Math.min(insertAt + 3, result.length)
    }

    const visibleSuggestions = feedData.followSuggestions.filter(s => !dismissedSuggestions.has(s.id))
    if (visibleSuggestions.length > 0) result.push({ kind: 'follow_suggestions', key: 'follow-suggestions' })

    // Hero card is always pinned first
    if (feedData.charts.some(c => c.category === 'overall')) {
      result.unshift({ kind: 'hero', key: 'hero-top-charts' })
    }

    return result
  }, [feedData, dismissedSuggestions])

  // ---------- persistence handlers ----------

  const updateLocalRating = (mediaId: string, rating: 'meh' | 'like' | 'love' | null) => {
    setFeedData(prev => {
      if (!prev) return prev
      const userRatings = { ...prev.userRatings }
      if (rating === null) delete userRatings[mediaId]
      else userRatings[mediaId] = rating
      return { ...prev, userRatings }
    })
  }

  const updateLocalStatus = (mediaId: string, status: 'want' | 'watching' | 'watched' | null) => {
    setFeedData(prev => {
      if (!prev) return prev
      const userStatuses = { ...prev.userStatuses }
      if (status === null) delete userStatuses[mediaId]
      else userStatuses[mediaId] = status
      return { ...prev, userStatuses }
    })
  }

  const handleRate = async (mediaId: string, rating: 'meh' | 'like' | 'love' | null) => {
    if (!user) return
    try {
      if (rating === null) {
        await supabase.from('ratings').delete().eq('user_id', user.id).eq('media_id', mediaId)
      } else {
        const { error } = await supabase.from('ratings').upsert({
          user_id: user.id,
          media_id: mediaId,
          rating
        }, { onConflict: 'user_id,media_id' })
        if (error) throw error
        trackMediaRated({
          media_id: mediaId,
          media_type: mediaId.startsWith('movie-') ? 'movie' : 'tv',
          media_title: detailShow?.title || mediaId,
          rating,
          season_number: mediaId.match(/-s(\d+)$/) ? parseInt(mediaId.match(/-s(\d+)$/)![1]) : undefined,
          has_comment: false
        })
      }
      updateLocalRating(mediaId, rating)
    } catch (err) {
      console.error('Error saving rating:', err)
    }
  }

  const handleSetStatus = async (mediaId: string, status: 'want' | 'watching' | 'watched' | null) => {
    if (!user) return
    try {
      const oldStatus = feedData?.userStatuses[mediaId] || null
      if (status === null) {
        await supabase.from('watch_status').delete().eq('user_id', user.id).eq('media_id', mediaId)
      } else {
        const { error } = await supabase.from('watch_status').upsert({
          user_id: user.id,
          media_id: mediaId,
          status
        }, { onConflict: 'user_id,media_id' })
        if (error) throw error
        // Unreleased show added to a list -> auto-set the release reminder
        if (status === 'want' || status === 'watching') {
          await ensureReleaseReminder(supabase, user.id, mediaId)
        }
      }
      trackWatchStatusChanged({
        media_id: mediaId,
        media_type: mediaId.startsWith('movie-') ? 'movie' : 'tv',
        media_title: detailShow?.title || mediaId,
        old_status: oldStatus as any,
        new_status: status as any,
        season_number: mediaId.match(/-s(\d+)$/) ? parseInt(mediaId.match(/-s(\d+)$/)![1]) : undefined
      })
      updateLocalStatus(mediaId, status)
    } catch (err) {
      console.error('Error saving status:', err)
    }
  }

  /** Ensure a media row exists for a TMDB title; returns the media row */
  const ensureMedia = async (tmdbId: number, mediaType: 'tv' | 'movie'): Promise<any | null> => {
    try {
      const res = await fetch('/api/media/ensure', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tmdbId, mediaType })
      })
      if (!res.ok) return null
      const data = await res.json()
      return data.media || null
    } catch {
      return null
    }
  }

  // ---------- show detail opening ----------

  const openShowFromDigest = (item: DigestShowItem) => {
    setDetailShow({
      id: item.mediaId,
      title: (item.title || '').replace(/\s*-\s*Season\s+\d+$/i, ''),
      posterUrl: item.posterPath ? `https://image.tmdb.org/t/p/w500${item.posterPath}` : undefined,
      year: item.year ? String(item.year) : undefined,
      genres: item.genres,
      rating: item.voteAverage || 0,
      synopsis: item.overview || '',
      mediaType: item.mediaType === 'movie' ? 'Movie' : 'TV',
      season: item.season || undefined,
      tmdb_id: item.tmdbId || undefined
    })
  }

  const openShowFromChart = async (entry: ChartEntry, chart: PlatformChart, chartType: 'tv' | 'movie') => {
    let mediaId = entry.dbMediaId
    let mediaRow: any = null
    if (mediaId) {
      // Known show - fetch the row so year/genres/synopsis populate
      const { data } = await supabase
        .from('media')
        .select('id, poster_path, overview, release_date, vote_average, tmdb_data')
        .eq('id', mediaId)
        .maybeSingle()
      mediaRow = data
    } else if (entry.tmdbId) {
      mediaRow = await ensureMedia(entry.tmdbId, chartType)
      mediaId = mediaRow?.id || null
    }
    if (!mediaId) return

    const namedGenres = mediaRow?.tmdb_data?.genres?.map((g: any) => g.name).slice(0, 3)
    const genres = namedGenres && namedGenres.length > 0
      ? namedGenres
      : mapGenreIds(mediaRow?.tmdb_data?.genre_ids)

    setDetailShow({
      id: mediaId,
      title: entry.title.replace(/:\s*(Season|Part|Volume|Chapter|Series)\s+\d+.*$/i, ''),
      posterUrl: (mediaRow?.poster_path || entry.posterPath)
        ? `https://image.tmdb.org/t/p/w500${mediaRow?.poster_path || entry.posterPath}`
        : undefined,
      year: mediaRow?.release_date ? mediaRow.release_date.substring(0, 4) : undefined,
      genres,
      rating: mediaRow?.vote_average || 0,
      synopsis: mediaRow?.overview || '',
      mediaType: chartType === 'movie' ? 'Movie' : 'TV',
      season: mediaId.match(/-s(\d+)$/) ? parseInt(mediaId.match(/-s(\d+)$/)![1]) : undefined,
      tmdb_id: entry.tmdbId || undefined
    })
  }

  const openUserProfile = (_userId: string, username: string) => {
    window.location.href = `/${username}`
  }

  // ---------- follow suggestions ----------

  const handleFollow = async (userId: string) => {
    if (!user) return
    try {
      const { data: existingFollow } = await supabase
        .from('follows')
        .select('id, status')
        .eq('follower_id', user.id)
        .eq('following_id', userId)
        .maybeSingle()

      if (!existingFollow) {
        const { error } = await supabase.from('follows').insert({
          follower_id: user.id,
          following_id: userId,
          status: 'accepted'
        })
        if (error) throw error

        const followed = feedData?.followSuggestions.find(s => s.id === userId)
        if (followed) {
          trackUserFollowed({
            followed_user_id: userId,
            followed_username: followed.username,
            followed_display_name: followed.name,
            follow_type: 'public'
          })
        }
      }
      setDismissedSuggestions(prev => new Set([...prev, userId]))
    } catch (err) {
      console.error('Error following user:', err)
    }
  }

  const handleDismissSuggestion = (userId: string) => {
    trackEvent('suggestion_dismissed', { dismissed_user_id: userId, source: 'find_friends_card' })
    setDismissedSuggestions(prev => new Set([...prev, userId]))
  }

  const handleMediaSelect = () => {
    // Search modal saves directly; refresh feed data lazily
    loadFeed()
  }

  // ---------- FeedCardData builders for recommendation cards ----------

  const buildVlyCardData = (item: VlyItem): FeedCardData => ({
    id: `vly-${item.mediaId}`,
    media: {
      id: item.mediaId,
      title: (item.title || '').replace(/\s*-\s*Season\s+\d+$/i, ''),
      year: item.year || new Date().getFullYear(),
      genres: item.genres,
      rating: item.voteAverage || 0,
      posterUrl: item.posterPath ? `https://image.tmdb.org/t/p/w500${item.posterPath}` : '',
      synopsis: item.overview || '',
      creator: '',
      cast: [],
      season: item.season || undefined,
      mediaType: item.mediaType === 'movie' ? 'Movie' : 'TV'
    },
    friends: { avatars: [], count: 0, text: '' },
    stats: { likeCount: 0, commentCount: 0, userLiked: false },
    friendsActivity: {
      watching: { count: 0, avatars: [] },
      wantToWatch: { count: 0, avatars: [] },
      watched: { count: 0, avatars: [] },
      ratings: { meh: 0, like: 0, love: 0, userRating: feedData?.userRatings[item.mediaId] }
    },
    comments: [],
    showComments: []
  })

  const buildBylCardData = (item: BylItem): FeedCardData => ({
    id: `byl-${item.tmdbId}`,
    media: {
      id: `${item.mediaType}-${item.tmdbId}`, // resolved to a season row on interaction
      title: item.title,
      year: item.year || new Date().getFullYear(),
      genres: mapGenreIds(item.genreIds),
      rating: item.voteAverage || 0,
      posterUrl: item.posterPath ? `https://image.tmdb.org/t/p/w500${item.posterPath}` : '',
      synopsis: item.overview || '',
      creator: '',
      cast: [],
      mediaType: item.mediaType === 'movie' ? 'Movie' : 'TV'
    },
    friends: { avatars: [], count: 0, text: '' },
    stats: { likeCount: 0, commentCount: 0, userLiked: false },
    friendsActivity: {
      watching: { count: 0, avatars: [] },
      wantToWatch: { count: 0, avatars: [] },
      watched: { count: 0, avatars: [] },
      ratings: { meh: 0, like: 0, love: 0 }
    },
    comments: [],
    showComments: []
  })

  const buildComingSoonCardData = (item: ComingSoonItem): FeedCardData => ({
    id: `cs-${item.mediaId}`,
    media: {
      id: item.mediaId,
      title: item.title,
      year: parseInt(item.airDate.substring(0, 4)) || new Date().getFullYear(),
      genres: item.genres,
      rating: item.voteAverage || 0,
      posterUrl: item.posterPath ? `https://image.tmdb.org/t/p/w500${item.posterPath}` : '',
      synopsis: item.overview || '',
      creator: '',
      cast: [],
      season: item.season || undefined,
      mediaType: 'TV'
    },
    friends: { avatars: [], count: 0, text: '' },
    stats: { likeCount: 0, commentCount: 0, userLiked: false },
    friendsActivity: {
      watching: { count: 0, avatars: [] },
      wantToWatch: { count: 0, avatars: [] },
      watched: { count: 0, avatars: [] },
      ratings: { meh: 0, like: 0, love: 0 }
    },
    comments: [],
    showComments: []
  })

  /** Rate/status handlers for BYL cards - resolve TMDB title to a real media row first */
  const handleBylRate = async (item: BylItem, rating: 'meh' | 'like' | 'love' | null) => {
    const media = await ensureMedia(item.tmdbId, item.mediaType)
    if (media) await handleRate(media.id, rating)
  }
  const handleBylStatus = async (item: BylItem, status: 'want' | 'watching' | 'watched' | null) => {
    const media = await ensureMedia(item.tmdbId, item.mediaType)
    if (media) await handleSetStatus(media.id, status)
  }

  const handleSetReminder = async (item: ComingSoonItem) => {
    if (!user) return
    try {
      await supabase.from('show_reminders').upsert({
        user_id: user.id,
        media_id: item.mediaId,
        season_number: item.season,
        air_date: item.airDate
      }, { onConflict: 'user_id,media_id,season_number' })
      trackEvent('reminder_set', { media_id: item.mediaId, air_date: item.airDate })
    } catch (err) {
      console.error('Error setting reminder:', err)
    }
  }

  const handleSubmitShowComment = async (mediaId: string, text: string) => {
    if (!user || !text.trim()) return
    try {
      await supabase.from('show_comments').insert({
        user_id: user.id,
        media_id: mediaId,
        comment_text: text.trim()
      })
    } catch (err) {
      console.error('Error submitting comment:', err)
    }
  }

  // ---------- render ----------

  if (loading) {
    return (
      <div style={{
        minHeight: '100vh',
        background: colors.bgGradient,
        paddingTop: '90px',
        paddingBottom: '120px',
        overflowX: 'hidden'
      }}>
        <style>{`
          @keyframes skeletonPulse {
            0%, 100% { opacity: 0.5; }
            50% { opacity: 1; }
          }
          .skeleton-card-wrapper {
            padding: 15px 8px;
            display: flex;
            justify-content: center;
          }
          .skeleton-card {
            width: 100%;
            max-width: 398px;
            height: 645px;
            border-radius: 16px;
            background: linear-gradient(160deg, rgba(255,255,255,0.08), rgba(255,255,255,0.03));
            animation: skeletonPulse 1.4s ease-in-out infinite;
            position: relative;
            overflow: hidden;
          }
          .skeleton-line {
            position: absolute;
            left: 20px;
            border-radius: 8px;
            background: rgba(255,255,255,0.1);
          }
        `}</style>
        <AppHeader profile={profile} hideOnScroll />
        {[0, 1].map(i => (
          <div key={i} className="skeleton-card-wrapper">
            <div className="skeleton-card">
              <div className="skeleton-line" style={{ bottom: 96, width: '55%', height: 22 }} />
              <div className="skeleton-line" style={{ bottom: 64, width: '38%', height: 14 }} />
            </div>
          </div>
        ))}
      </div>
    )
  }

  if (error && !feedData) {
    return (
      <div style={{
        minHeight: '100vh',
        background: colors.bgGradient,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: colors.textPrimary,
        flexDirection: 'column',
        gap: '16px'
      }}>
        <div>Error: {error}</div>
        <a href="/auth" style={{ color: '#3b82f6' }}>Go to Login</a>
      </div>
    )
  }

  const currentUserForCards = profile ? {
    id: user?.id || '',
    name: profile.display_name || profile.username || '',
    avatar: profile.avatar_url || ''
  } : undefined

  return (
    <div style={{ background: colors.bgGradient, minHeight: '100vh', paddingTop: '90px', paddingBottom: '120px', overflowX: 'hidden' }}>
      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }

        .card-snap-wrapper {
          scroll-snap-align: center;
          scroll-snap-stop: always;
          padding: 15px 0;
          display: flex;
          justify-content: center;
          align-items: center;
        }

        .card-inner-wrapper {
          width: 100%;
          max-width: 398px;
          display: flex;
          justify-content: center;
          padding: 0 8px;
        }
      `}</style>

      <AppHeader profile={profile} hideOnScroll />

      {showInviteCodeGate && user?.id && (
        <InviteCodeGate
          userId={user.id}
          onSuccess={() => {
            setShowInviteCodeGate(false)
            setShowProfileSetup(true)
          }}
        />
      )}

      {showProfileSetup && profile && user?.id && (
        <ProfileSetup
          userId={user.id}
          initialUsername={profile.username || ''}
          initialDisplayName={profile.display_name || ''}
          userEmail={user?.email || ''}
          onComplete={(updatedProfile) => {
            setProfile({
              ...profile,
              username: updatedProfile.username,
              display_name: updatedProfile.display_name
            })
            setShowProfileSetup(false)
          }}
        />
      )}

      <div>
        {blocks.length === 0 && (
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '80px 20px',
            gap: '12px',
            color: colors.textPrimary
          }}>
            <div style={{ fontSize: '18px', fontWeight: 700 }}>Nothing here yet</div>
            <div style={{ color: colors.textSecondary, fontSize: '14px', textAlign: 'center' }}>
              Follow some friends or add shows to your lists to fill your feed.
            </div>
          </div>
        )}

        {blocks.map((block) => {
          if (block.kind === 'digest') {
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <FriendDigestCard
                    digest={block.digest}
                    onShowClick={openShowFromDigest}
                    onUserClick={openUserProfile}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'hero') {
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <HeroTopChartsCard
                    charts={feedData?.charts ?? []}
                    onShowClick={openShowFromChart}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'chart') {
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <PlatformChartCard
                    chart={block.chart}
                    chartType={block.chartType}
                    onShowClick={openShowFromChart}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'vly') {
            const item = block.item
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <FeedCard
                    variant="b"
                    data={buildVlyCardData(item)}
                    badges={[{
                      text: item.supporters > 1
                        ? `${item.supporters} viewers like you loved this`
                        : 'Viewers like you loved this',
                      icon: 'heart',
                      color: 'rgba(255, 193, 37, 0.22)',
                      borderColor: 'rgba(255, 193, 37, 0.55)',
                      textColor: 'white'
                    }]}
                    currentUser={currentUserForCards}
                    initialUserStatus={feedData?.userStatuses[item.mediaId]}
                    onRate={handleRate}
                    onSetStatus={handleSetStatus}
                    onSubmitShowComment={handleSubmitShowComment}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'byl') {
            const item = block.item
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <FeedCard
                    variant="b"
                    data={buildBylCardData(item)}
                    badges={[BADGE_PRESETS.BECAUSE_YOU_LIKED(item.sourceTitle)]}
                    currentUser={currentUserForCards}
                    onRate={(_, rating) => handleBylRate(item, rating)}
                    onSetStatus={(_, status) => handleBylStatus(item, status)}
                    onSubmitShowComment={handleSubmitShowComment}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'coming_soon') {
            const item = block.item
            const formattedDate = new Date(item.airDate + 'T00:00:00').toLocaleDateString('en-US', {
              month: 'short',
              day: 'numeric',
              year: 'numeric'
            })
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <FeedCard
                    variant="b"
                    backVariant="unreleased"
                    data={buildComingSoonCardData(item)}
                    badges={[BADGE_PRESETS.COMING_SOON(formattedDate)]}
                    currentUser={currentUserForCards}
                    initialUserStatus={feedData?.userStatuses?.[item.mediaId] ?? null}
                    onSetReminder={() => handleSetReminder(item)}
                    onRemindMe={() => handleSetReminder(item)}
                    onSetStatus={handleSetStatus}
                  />
                </div>
              </div>
            )
          }

          if (block.kind === 'follow_suggestions' && feedData) {
            const visible = feedData.followSuggestions.filter(s => !dismissedSuggestions.has(s.id))
            if (visible.length === 0) return null
            return (
              <div key={block.key} className="card-snap-wrapper">
                <div className="card-inner-wrapper">
                  <FollowSuggestionsCard
                    suggestions={visible}
                    colorTheme="purple"
                    onFollow={handleFollow}
                    onDismiss={handleDismissSuggestion}
                    onUserClick={(userId) => {
                      const s = feedData.followSuggestions.find(x => x.id === userId)
                      if (s) window.location.href = `/${s.username}`
                    }}
                    onTrack={(action, metadata) => trackEvent(action, metadata)}
                  />
                </div>
              </div>
            )
          }

          return null
        })}
      </div>

      {blocks.length > 0 && (
        <div style={{ padding: '20px', textAlign: 'center', color: 'rgba(255,255,255,0.4)', fontSize: '14px' }}>
          You're all caught up
        </div>
      )}

      <div style={{ height: '20px' }} />

      <BottomNav onSearchOpen={() => setSearchOpen(true)} />

      {/* Show detail (opened from digest/chart rows) */}
      {detailShow && (
        <ShowDetailCard
          isOpen={true}
          onClose={() => setDetailShow(null)}
          media={detailShow}
          currentUser={currentUserForCards ? {
            id: currentUserForCards.id,
            name: currentUserForCards.name,
            avatar: currentUserForCards.avatar || null
          } : undefined}
          initialRating={feedData?.userRatings[detailShow.id] || null}
          initialStatus={feedData?.userStatuses[detailShow.id] || null}
          onRate={handleRate}
          onSetStatus={handleSetStatus}
        />
      )}

      <SearchModalEnhanced
        isOpen={searchOpen}
        onClose={() => setSearchOpen(false)}
        onSelectMedia={handleMediaSelect}
        user={user}
        profile={profile}
      />
    </div>
  )
}
