-- Create recommendations table for storing calculated recommendations
-- Recommendations are generated by the recommendation engine and shown in the feed

CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  media_id TEXT REFERENCES media(id),
  score REAL NOT NULL,
  algorithm_type TEXT CHECK (algorithm_type IN ('collaborative', 'content_based', 'hybrid')),
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  shown_at TIMESTAMPTZ,
  interacted_at TIMESTAMPTZ,
  UNIQUE(user_id, media_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_recommendations_user_score ON recommendations(user_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_recommendations_user_shown ON recommendations(user_id, shown_at);
CREATE INDEX IF NOT EXISTS idx_recommendations_media ON recommendations(media_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_created_at ON recommendations(created_at DESC);

-- Enable Row Level Security
ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own recommendations
CREATE POLICY "Users can view own recommendations"
  ON recommendations
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: System can insert recommendations (for background jobs)
CREATE POLICY "System can insert recommendations"
  ON recommendations
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Policy: Users can update their own recommendations (e.g., mark as shown)
CREATE POLICY "Users can update own recommendations"
  ON recommendations
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy: Users can delete their own recommendations
CREATE POLICY "Users can delete own recommendations"
  ON recommendations
  FOR DELETE
  USING (auth.uid() = user_id);

-- Add helpful comment
COMMENT ON TABLE recommendations IS 'Stores personalized media recommendations for users based on collaborative and content-based filtering';

